# Generated by Django 4.2.7 on 2025-11-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('Sanctioned', 'Sanctioned'), ('Shadow', 'Shadow'), ('Unknown', 'Unknown')], default='Unknown', max_length=50)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('entra_service_principal_id', models.CharField(blank=True, max_length=255)),
                ('entra_app_id', models.CharField(blank=True, max_length=255)),
                ('entra_publisher_name', models.CharField(blank=True, max_length=255)),
                ('entra_sign_in_audience', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'visibility_ai_asset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(blank=True, choices=[('Direct', 'Direct'), ('Integration', 'Integration'), ('Indirect', 'Indirect')], max_length=50)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'visibility_asset_relationship',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiscoverySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('AzureAD', 'Azure AD'), ('Survey', 'Survey'), ('CSV', 'CSV Import')], max_length=50)),
                ('collection_date', models.DateTimeField(auto_now_add=True)),
                ('confidence_level', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'visibility_discovery_source',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kovrr_vendor_id', models.CharField(blank=True, max_length=255)),
                ('risk_score', models.IntegerField(blank=True, null=True)),
                ('financial_exposure_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('financial_exposure_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('incident_history_ref', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'visibility_risk_profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsageIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('active_users_count', models.IntegerField(default=0)),
                ('trend_status', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'visibility_usage_indicator',
                'managed': False,
            },
        ),
    ]
