# Generated by Django 4.2.7 on 2025-11-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'risk_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('maturity_level', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'risk_control',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'risk_framework',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'risk_note',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiskScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('likelihood', models.CharField(blank=True, choices=[('Rare', 'Rare'), ('Unlikely', 'Unlikely'), ('Possible', 'Possible'), ('Likely', 'Likely'), ('Almost Certain', 'Almost Certain')], max_length=50)),
                ('impact', models.CharField(blank=True, choices=[('Negligible', 'Negligible'), ('Minor', 'Minor'), ('Moderate', 'Moderate'), ('Major', 'Major'), ('Severe', 'Severe')], max_length=50)),
                ('priority', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=50)),
                ('status', models.CharField(choices=[('Identified', 'Identified'), ('Analyzing', 'Analyzing'), ('Mitigating', 'Mitigating'), ('Monitoring', 'Monitoring'), ('Closed', 'Closed')], default='Identified', max_length=50)),
                ('response_plan', models.CharField(blank=True, choices=[('Mitigate', 'Mitigate'), ('Accept', 'Accept'), ('Avoid', 'Avoid'), ('Transfer', 'Transfer')], max_length=50)),
                ('annual_likelihood', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peer_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('financial_loss_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('financial_loss_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('pii_exposure', models.IntegerField(default=0)),
                ('pci_exposure', models.IntegerField(default=0)),
                ('phi_exposure', models.IntegerField(default=0)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('mitigation_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ticket_link', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'risk_scenario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScenarioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'risk_scenario_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScenarioControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_status', models.CharField(blank=True, choices=[('Compliant', 'Compliant'), ('Partial', 'Partial'), ('Non-Compliant', 'Non-Compliant'), ('Not Applicable', 'Not Applicable')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'risk_scenario_control',
                'managed': False,
            },
        ),
    ]
